### PR TITLE
"Competitive programming Levels Wise - CPLW" Lab Solutions for Third Year Students

### PR DESCRIPTION
**Pull request by DevGoyalG**

### CODE REVIEW

**Comment by DevGoyalG** [comment]
Hello Bhaiya,
I'm Dev Goyal. Pre Final Year B. Tech Student at NIET. I raise a PR on your "[niet_codetantra](https://github.com/krsatyam7/niet_codetantra)" repo. Please accept it, I added a folder named as "Competitive programming Levels Wise - CPLW", this module is introduced in session 2024-25.

Thanks and regards,
Dev Goyal

**Comment by krsatyam7** [comment]
> Hello Bhaiya, I'm Dev Goyal. Pre Final Year B. Tech Student at NIET. I raise a PR on your "[niet_codetantra](https://github.com/krsatyam7/niet_codetantra)" repo. Please accept it, I added a folder named as "Competitive programming Levels Wise - CPLW", this module is introduced in session 2024-25.
> 
> Thanks and regards, Dev Goyal

Hello Dev,

Thank you for your contribution! I’ve already noticed your PR and appreciate the effort you put into adding the "Competitive Programming Levels Wise - CPLW" folder for the new 2024-25 module. Due to the busy festive season, I haven't been able to address it yet, but I’ll be merging all pending PRs soon. Thanks again for your patience and valuable addition to the repo.

**Comment by DevGoyalG** [comment]
Oh okey bhaiya. No issues, whenever you will free you can merge the PR.

Thanks for your response bhaiya!

**Review by krsatyam7 — APPROVED** [review]

**Comment by DevGoyalG** [comment]
> Dev, I have merged all PRs. Please check.

Yeah, I checked bhaiya. Thanks for merging. I'll add more solutions in this one folder soon.

**Pull request merged**
