### PR TITLE
Update contiguousAllocationTech.c

### PR DESCRIPTION
**Pull request by DevGoyalG**
Hello!
I'm Dev Goyal. Second year CSE (AIML) student at NIET. I use this repository to complete my codetantra labs. This file is not working in codetantra properly due to lack of code. So, I update your "contiguousAllocationTech.c" Repository file. Merge this pull request. Still you want to change anything you can do it after merging this pull request.

Thanks and Regards,
Dev Goyal

### CODE REVIEW

**Comment by krsatyam7** [comment]
Thanks for your contribution, Dev! Merging now. 🚀

**Comment by DevGoyalG** [comment]
My Pleasure Bhaiya! 😇

Thanks for merging these PRs.

**Comment by krsatyam7** [comment]
Thanks for your contribution! I am looking forward to seeing more from you in the future. Keep up the great work! 👍

**Comment by DevGoyalG** [comment]
It was my pleasure! Yes I'll update as per requirement in future. Thank You
Bhaiya 😌

**Pull request merged**
